### ISSUE TITLE
Don't have write access

### ISSUE THREAD

**Issue by kevinvavelin** [OpenClassrooms-Student-Center/community#22]
Hello Team !

I don't have write access for this repository to accept the pull request from my students :) And the bot seems to not merge his pull request automatically : https://github.com/OpenClassrooms-Student-Center/community/pull/4

Can someone act on it for me ?

Kind regards,
Kevin Vavelin

**Comment by lorytif** [comment]
La pull request n'est pas passé car multiples erreurs de l'étudiant (nom de fichiers, description)
